name: dart_bulma_chat_app
description: A chat application written in Dart and styled with the Bulma CSS Framework.
version: 1.0.0
author: Jermaine Oppong <email@example.com>

environment:
  sdk: '>=2.16.1 <3.0.0'


# dependencies:
#   path: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0

